name: Run tests

on:
  push:
    branches: [main]
     
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: action/checkout@v1
    - name: Instalar as dependencias do server
      uses: bahmutov/npm-install@v1
      with:
        working-directory: server
    - name: Instalar as dependencias da web
      uses: bahmutov/npm-install@v1
      with:
        working-directory: web        
    - name: Component & AOI & UI Tests
      uses: cypress-io/github-actions@v2
      with:
         working-directory: web      
         install: false
         start: npm run start:ci
         wait-on: 'http://localhost:3000'
         


